development:
  adapter: postgresql
  encoding: unicode
  database: dev_postgres
  pool: 5
  username: postgres
  password:
  host: herokuPostgresql

test:
  adapter: postgresql
  encoding: unicode
  database: test_postgres
  pool: 5
  username: postgres
  password:
  host: herokuPostgresql
